# 应用配置
app:
  name: "Code Repo Learner"
  version: "0.1.0"
  debug: true
  verbose: false
  data_dir: "./data"
  logs_dir: "./logs"
  cache_dir: "./cache"

# 数据库配置
database:
  neo4j:
    uri: "bolt://localhost:7687"
    user: "neo4j"
    database: "neo4j"
  sqlite:
    path: "./data/metadata.db"

# 向量数据库配置
vector_store:
  chroma:
    persist_directory: "./data/chroma"
    collection_name: "code_embeddings"

# LLM配置
llm:
  embedding:
    model_name: "jinaai/jina-embeddings-v2-base-code"
    cache_dir: "~/.cache/torch/sentence_transformers/"
    batch_size: 32
  chat:
    api_key: "test_key"
    base_url: "https://openrouter.ai/api/v1/chat/completions"
    model: "google/gemini-2.0-flash-001"
    max_tokens: 8192
    temperature: 1.0
    top_p: 0.95

# 解析器配置
parser:
  tree_sitter:
    language: "c"
  file_patterns:
    include: ["*.c", "*.h"]
    exclude: ["*test*", "*example*", "*.bak"]
  options:
    max_file_size: 10485760
    encoding: "utf-8"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file:
    enabled: true
    path: "./logs/code_learner.log"
    max_size: "10MB"
    backup_count: 5
  console:
    enabled: true
    level: "INFO"

# 性能配置
performance:
  max_workers: 4
  cache:
    enabled: true
    ttl: 3600
    max_size: 1000
  batch:
    embedding_batch_size: 32
    parsing_batch_size: 10